import 'package:flutter/material.dart';

enum PhotoCategory {
  all,
  screenshots,
  documents,
  children,
  people,
  pets,
  animals,
  flowers,
  eyeglasses,
  food,
  transportation,
  clothing,
  shoes,
  vehicles,
  cars,
  architecture,
  sky,
  electronics,
  sportsExercise,
  nature,
  uncategorized,
}

extension PhotoCategoryExt on PhotoCategory {
  String get label => switch (this) {
    PhotoCategory.all => 'All',
    PhotoCategory.screenshots => 'Screenshots',
    PhotoCategory.documents => 'Documents',
    PhotoCategory.children => 'Children',
    PhotoCategory.people => 'People',
    PhotoCategory.pets => 'Pets',
    PhotoCategory.animals => 'Animals',
    PhotoCategory.flowers => 'Flowers',
    PhotoCategory.eyeglasses => 'Eyeglasses',
    PhotoCategory.food => 'Food',
    PhotoCategory.transportation => 'Transportation',
    PhotoCategory.clothing => 'Skirts & dresses',
    PhotoCategory.shoes => 'Shoes',
    PhotoCategory.vehicles => 'Vehicles',
    PhotoCategory.cars => 'Cars',
    PhotoCategory.architecture => 'Architecture',
    PhotoCategory.sky => 'Sky',
    PhotoCategory.electronics => 'Electronics',
    PhotoCategory.sportsExercise => 'Sports & exercise',
    PhotoCategory.nature => 'Nature',
    PhotoCategory.uncategorized => 'Other',
  };

  IconData get icon => switch (this) {
    PhotoCategory.all => Icons.image_outlined,
    PhotoCategory.screenshots => Icons.crop_free,
    PhotoCategory.documents => Icons.description_outlined,
    PhotoCategory.children => Icons.child_care,
    PhotoCategory.people => Icons.person_outline,
    PhotoCategory.pets => Icons.pets,
    PhotoCategory.animals => Icons.cruelty_free,
    PhotoCategory.flowers => Icons.local_florist_outlined,
    PhotoCategory.eyeglasses => Icons.visibility_outlined,
    PhotoCategory.food => Icons.restaurant_outlined,
    PhotoCategory.transportation => Icons.directions_transit,
    PhotoCategory.clothing => Icons.checkroom_outlined,
    PhotoCategory.shoes => Icons.hiking,
    PhotoCategory.vehicles => Icons.two_wheeler,
    PhotoCategory.cars => Icons.directions_car_outlined,
    PhotoCategory.architecture => Icons.apartment,
    PhotoCategory.sky => Icons.cloud_outlined,
    PhotoCategory.electronics => Icons.phone_android,
    PhotoCategory.sportsExercise => Icons.sports_soccer,
    PhotoCategory.nature => Icons.park_outlined,
    PhotoCategory.uncategorized => Icons.folder_outlined,
  };

  Color get color => switch (this) {
    PhotoCategory.all => const Color(0xFF18D0B8),
    PhotoCategory.screenshots => const Color(0xFF18D0B8),
    PhotoCategory.documents => const Color(0xFFFFB41B),
    PhotoCategory.children => const Color(0xFF7C54E8),
    PhotoCategory.people => const Color(0xFF9A45D7),
    PhotoCategory.pets => const Color(0xFFD99A20),
    PhotoCategory.animals => const Color(0xFF48C35A),
    PhotoCategory.flowers => const Color(0xFFE95D73),
    PhotoCategory.eyeglasses => const Color(0xFF2E9DCC),
    PhotoCategory.food => const Color(0xFFE76F51),
    PhotoCategory.transportation => const Color(0xFF64748B),
    PhotoCategory.clothing => const Color(0xFFC83878),
    PhotoCategory.shoes => const Color(0xFFD04B58),
    PhotoCategory.vehicles => const Color(0xFF4777C9),
    PhotoCategory.cars => const Color(0xFF2FB65E),
    PhotoCategory.architecture => const Color(0xFFD99A20),
    PhotoCategory.sky => const Color(0xFF2E9DCC),
    PhotoCategory.electronics => const Color(0xFF18D0B8),
    PhotoCategory.sportsExercise => const Color(0xFF10B981),
    PhotoCategory.nature => const Color(0xFF48C35A),
    PhotoCategory.uncategorized => const Color(0xFF8B94A3),
  };
}
